### PR TITLE
[WIP] script to check that all required software has been installed

### PR DESCRIPTION
**Pull request by llevitis**
This script is inspired by the one made for McGill's Foundations of Neuro Data Science course. (https://github.com/neurodatascience/course-2020/blob/master/static/resources/nds_check_install.sh)

I am using Mac OS, so we'll need to have this tested for Linux and Windows. 

Tested on:
- [x] Mac OS
- [x] Linux 
- [x] Windows

To-do: 
- [x] Create check for Octave
- [ ] Create check for Matlab (unless we will only be using Octave)
- [x] Update the required packages once we've finalized the TrainTrack content

### CODE REVIEW

**Comment by Remi-Gau** [comment]
This is really cool. 

And also and good example of a short script with bash functions.

Works fine on linux. Ticked the relevant box in the list in the PR.

**Comment by Remi-Gau** [comment]
@llevitis should we test this on windows somehow?

**Comment by anibalsolon** [comment]
It goes fine on Windows (with the Linux subsystem) 👏 

image

**Comment by Remi-Gau** [comment]
tempted to merge this for now and open an issue to say that this needs improvement for matab / octave

@llevitis what do you think?

**Comment by llevitis** [comment]
> tempted to merge this for now and open an issue to say that this needs improvement for matab / octave
> 
> @llevitis what do you think?

I think Agah said we'll only be using Octave, and I did add a check for that, so yes I think we can merge!! You can do the honours :D

**Pull request merged**
