### PR TITLE
Add a select box to interactively update times according to selected timezone

### PR DESCRIPTION
**Pull request by crohr**
Add a separate schedule page for each hub (with corresponding data file), as well as a select box to allow modifying the timezone in which the times are rendered.

### CODE REVIEW

**Comment by cmaumet** [comment]
Thank you so much @crohr!

**Comment by cmaumet** [comment]
Thanks @Remi-Gau! The plan is next to create a schedule page per hub so that the timezone selecter will work for all hubs (currently centered around Apac only), this will also let us have differences in the 3 schedules as discussed with hubs co-hosts.

**Comment by Remi-Gau** [comment]
okidoki.
I could help with that but need to tick a few other things from my to do list first.

**Comment by cmaumet** [comment]
Thank you @crohr!

@Remi-Gau, @llevitis: Let us know how you feel about this update to add a timezone selecter to the schedule. Hopefully we can build onto that structure? Thanks!

**Comment by Remi-Gau** [comment]
so far I am liking what I am seeing. A LOT.

thank you so much for this

will double check tomorrow but am pretty sure this will be an LGTM. :-)

**Comment by cmaumet** [comment]
Thanks for approving @Remi-Gau! I'll merge this now so that I can share with OSR team and see if could use a similar setup for their schedule.

**Pull request merged**
