### PR TITLE
update project template

### PR DESCRIPTION
**Pull request by Remi-Gau**
- move additional project info above the project submission check list as it makes it easier for attendees to get all the information about a project
- use markdown comments to hide things that we don't want to display in the end

### CODE REVIEW

**Comment by Remi-Gau** [comment]
@cmaumet is that ok for you?

**Comment by cmaumet** [comment]
@Remi-Gau: I like the clarity this brings but wondering if we could keep some of the info uncommented (in particular the list 1-4 that describes the overall workflow). My worry is that once the issue is submitted it might be harder for project lead to retreive that info (i.e. see that this is still there but commented out). How about we keep the top part but as part of 4 we ask the project lead to delete the 'instructions' at the top of the issue? I'm happy to draft that but would like for us to converge first.

**Comment by Remi-Gau** [comment]
Yes that sounds like a good plan. :-)

Will let you adapt.

**Comment by cmaumet** [comment]
How is that?

**Comment by Remi-Gau** [comment]
go for it. :-)

**Pull request merged**
