### PR TITLE
Make the hackathon website more accessible

### PR DESCRIPTION
**Pull request by cmaumet**
To make the hackathon website more accessible from different places in the world, this PR:
 - Use cdnjs to retreive jquery
 - Use default fonts
 - Remove all call to "https://apis.google.com"

The website (and its template) still relies on a number of google services (e.g. Google maps, Google plus in places, etc.) but I'm hoping those remaining calls will not prevent the website from loading.

@Remi-Gau, @llevitis: I've tested on my machine and I *think* the website still works as expected, it would be good to have one of you checking as you know the website best. Thanks!

### CODE REVIEW

**Comment by Remi-Gau** [comment]
Also google plus is officially dead so I guess we can remove those.

And I don't think we will keep google maps stuff.

**Comment by llevitis** [comment]
> This looks good to me.
> 
> There is a bit of weird rendering on the schedule page but I think we can fix this when we take of this page.
> @llevitis what do you say?

The schedule page doesn't seem to be rendering weirdly on my end. This looks good to me :) Thanks @cmaumet !!

**Comment by Remi-Gau** [comment]
will merge

**Comment by cmaumet** [comment]
Great! Thank you for the merge!

**Pull request merged**
