### PR TITLE
Add phys2bids project

### PR DESCRIPTION
**Pull request by smoia**
I'd like to add the project snippet for #193 .
Since the project is in two hubs, how should that field be formatted?

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@smoia looks like the project was already added to the website:
https://github.com/ohbm/hackathon2020/blob/master/_data/projects.yml#L307

in commit 5dd9e70 :+1: 

See:
https://ohbm.github.io/hackathon2020/hackathon/

Check if how the hub is presented seems OK to you :question: . If it is OK, and if this sounds OK to you :question: , then we will need to close this PR without being merged.

**Comment by smoia** [comment]
I'm sorry - I didn't see it!

Would it be possible to change the description in the website, like this:
```
details: "<a href="https://github.com/physiopy/phys2bids">Physiopy</a> is a github organisation that aims to offer open development solutions for physiology in MRI.
  <a href="https://github.com/physiopy/phys2bids">phys2bids</a> is the flagship library of physiopy, and it consists in a python3 library meant to format physiological
  (cardiac, respiratory, or gas signals) files in BIDS. <br>During this hackathon, we would love to involve new contributors to integrate new features, such as
  automatic recognition of the file content, support for eyetracking, and integration with other bidsificators (such as <a href="https://bidscoin.readthedocs.io">bidscoin</a>) 
  Next to phys2bids, we’re starting the development of phys2denoise, a library dedicated to prepare physiological signal for fMRI denoising.
  <br>More information <a href=https://github.com/ohbm/hackathon2020/issues/193>in this github issue</a>"
```
I modified it in this PR, but if it's not too much trouble to change it and it's more practical to change it someway else, better!

**Comment by jhlegarreta** [comment]
@smoia it's fine to modify it :+1: However, the quotes in the hyper-links seem not to be supported by the system, e.g.
`<a href="https://github.com/physiopy/phys2bids">Physiopy</a>` to
`<a href=https://github.com/physiopy/phys2bids>Physiopy</a>`

and so on. Will you change them, please? Thanks !

**Comment by jhlegarreta** [comment]
@smoia thanks :tada: ! Tests are passing. Merging.

**Pull request merged**
