### PR TITLE
[WIP] Schedule page

### PR DESCRIPTION
**Pull request by Remi-Gau**
Here is a draft of a 'typical' hackathon.

Now is the question of how we want to display that for each time zone...

Oh I went to to town with the session descriptions: they don't have to be final.

### CODE REVIEW

**Comment by Remi-Gau** [comment]
Also I am not sure that we will be able to fit all the things we wanted given the number of hours we have: I could not fit the nilearn session for example.

And if sponsors want one session we are in trouble. :-/

**Comment by cmaumet** [comment]
@Remi-Gau: we can add more activities that will be asynchroneous for people to look at before and after the 6-hours of common program?

**Comment by Remi-Gau** [comment]
> @Remi-Gau: we can add more activities that will be asynchroneous for people to look at before and after the 6-hours of common program?

good point

**Comment by cmaumet** [comment]
Sorry, I did not mean we have to do this now... I was trying to say this could be a partial solution to the "too much content" issue ;)

**Comment by Remi-Gau** [comment]
> Sorry, I did not mean we have to do this now... I was trying to say this could be a partial solution to the "too much content" issue ;)

No worries: just filed it on my to do list. Current rank is: 13535. 

I will get to it.

Eventually

**Comment by cmaumet** [comment]
Hi Remi! Here is a more lighweight version in which we indicate at the top the name of three cities (one per hub) in which the indicated time is local time (Bankgok, London, Los Angeles). I find this easier to read than my initial proposal. What do you think?

Screen Shot 2020-05-08 at 08 10 34

**Comment by cmaumet** [comment]
> Oh I went to to town with the session descriptions: they don't have to be final.

Finally been through those! Really nice <3

> And if sponsors want one session we are in trouble. :-/

Maybe some could help with one of the prpoposed trainttrack sessions. We could also add optional sessions during the hack times for those sponsor sessions (e.g. for some might be a discussion more than training)?

**Comment by Remi-Gau** [comment]
Thank you so much for this.

Will have a look now. :-)

**Comment by Remi-Gau** [comment]
Putting only towns that have the same time: this is a great idea.

Will try to see if I can add towns from each hemisphere.

I am getting some weird layout on that top cell. But only with firefox...

Screenshot 2020-05-08 15:51:53

**Comment by Remi-Gau** [comment]
This is good with me.
@llevitis what do you think?

**Comment by llevitis** [comment]
> Maybe some could help with one of the prpoposed trainttrack sessions. We could also add optional sessions during the hack times for those sponsor sessions (e.g. for some might be a discussion more than training)?

Yes, this is definitely something to keep in mind! Perhaps next week Remi and i can reach out to those sponsors who are "hackathon champions" to see what ideas they have had.

**Comment by llevitis** [comment]
> > Maybe some could help with one of the prpoposed trainttrack sessions. We could also add optional sessions during the hack times for those sponsor sessions (e.g. for some might be a discussion more than training)?
> 
> Yes, this is definitely something to keep in mind! Perhaps next week Remi and i can reach out to those sponsors who are "hackathon champions" to see what ideas they have had.

**Comment by llevitis** [comment]
did not mean to close it....

**Comment by llevitis** [comment]
This looks really great @Remi-Gau ! I say that we merge this, and then we can update the schedule as we get a clearer sense of which ReproNim trainees are interested in teaching and what sponsors would like to see as well. What do you think?

**Comment by Remi-Gau** [comment]
ok I will fix this merge conflict and merge.

**Pull request merged**
