### PR TITLE
Add BIDS Curation GUI

### PR DESCRIPTION
**Pull request by AndysWorth**
How's this?

Thanks!

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@AndysWorth sounds awesome ! For the image to be displayed in the website, it needs to be placed [here](https://github.com/ohbm/hackathon2020/tree/master/img/hackathon). Could you please add the image within this PR?

**Comment by jhlegarreta** [comment]
@AndysWorth it looks like this overlaps with PR #190. The latter PR seems to have the image that is missing in this PR. Could you please add it here and confirm that we can then close PR #190 without being merged? Thanks :rocket: !

**Comment by AndysWorth** [comment]
Yes, I did a separate PR for just the image and then this one.  #190 ca be closed without merge.  Thanks!

**Comment by jhlegarreta** [comment]
@AndysWorth thanks. Note that the image needs to be placed in:
https://github.com/ohbm/hackathon2020/tree/master/img/hackathon

Could you move the image to there and amend your previous commit, please?

**Comment by Remi-Gau** [comment]
@AndysWorth I fixed a couple of details. YML files can be annoying with double quotes.

Also moved the image t the right folder and rebased the whole thing.

Thanks @AndysWorth for submitting and thanks @jhlegarreta for checking all this. :pray:

**Pull request merged**
