### PR TITLE
[WIP] traintrack page

### PR DESCRIPTION
**Pull request by Remi-Gau**
# goal
creating a traintrack page

### CODE REVIEW

**Comment by Remi-Gau** [comment]
@llevitis trying to reuse most of the template of the website to see how it covers our needs.

**Comment by Remi-Gau** [comment]
@llevitis I think there should be a smart way to reuse some of the content from the _volunteers.yml file for this, no?

I have added the images of the sessions in each frame.

I will refactor the the speakers.yml file a bit to help in the future

**Comment by llevitis** [comment]
> @llevitis I think there should be a smart way to reuse some of the content from the _volunteers.yml file for this, no?
> 
> I have added the images of the sessions in each frame.
> 
> I will refactor the the speakers.yml file a bit to help in the future

There probably is a smarter way, but this might be one of those problems that would take more time figuring out an elegant solution for lol

**Comment by Remi-Gau** [comment]
> > @llevitis I think there should be a smart way to reuse some of the content from the _volunteers.yml file for this, no?
> > I have added the images of the sessions in each frame.
> > I will refactor the the speakers.yml file a bit to help in the future
> 
> There probably is a smarter way, but this might be one of those problems that would take more time figuring out an elegant solution for lol

Wait... Are you saying we are short on time? LOL

**Comment by Remi-Gau** [comment]
@anibalsolon this looks fantastic !!!

I have made sure that the speakers and TAs images were grabbed from the right folder.

The session modal display the session image when no video is there.

**to do**
- [ ] make the session image is much smaller (height = 400px ?)
- [ ] add TAs to modal
- [ ] add listing of TAs for each session

I suspect that we might have some different codes and slides for different speakers so maybe those should be reinjected in the speakers loop of the modal.

@llevitis I am going to take care of the the third point above but you might want to cross-check what I input because you are more aware of who teaches what than I am. :wink:

**Comment by Remi-Gau** [comment]
We might want to create a separate branch we will push into production when we go "live" : e.g with youtube links.

**Comment by anibalsolon** [comment]
@Remi-Gau I guess I am done 🙆‍♂️ If you think of any improvement, please give me a :telephone_receiver:

**Comment by llevitis** [comment]
@anibalsolon thank you so much for all the updates!! I will add info for the INCF session and update some speaker info

**Comment by Remi-Gau** [comment]
@cmaumet can you check out this when you have time.

**Pull request merged**
